export const productSamples = [
  {
    id: 1,
    slug: "apple",
    name: "Apple",
    icon: "Apple",
    category: "Fruit",
    grade: "Grade A",
    supplier: "Fresh Farms",
    price: 214,
    compareAt: 250,
    stock: 700,
    moq: 5,
    unit: "kg",
    origin: "Himachal Pradesh",
    delivery: "Tomorrow",
    rating: "4.8",
  },
  {
    id: 2,
    slug: "mango",
    name: "Mango",
    icon: "Mango",
    category: "Fruit",
    grade: "Grade A",
    supplier: "Green Farm",
    price: 150,
    compareAt: 180,
    stock: 420,
    moq: 10,
    unit: "kg",
    origin: "India",
    delivery: "Tomorrow",
    rating: "4.8",
  },
  {
    id: 3,
    slug: "orange",
    name: "Orange",
    icon: "Orange",
    category: "Fruit",
    grade: "Grade A",
    supplier: "Supplier C",
    price: 180,
    compareAt: 210,
    stock: 500,
    moq: 20,
    unit: "kg",
    origin: "India",
    delivery: "Tomorrow",
    rating: "4.7",
  },
  {
    id: 4,
    slug: "banana",
    name: "Banana",
    icon: "Banana",
    category: "Fruit",
    grade: "Standard",
    supplier: "Supplier D",
    price: 60,
    compareAt: 75,
    stock: 900,
    moq: 5,
    unit: "dozen",
    origin: "India",
    delivery: "Tomorrow",
    rating: "4.5",
  },
];

export const categories = ["Fruits", "Vegetables", "Dairy", "Rice", "Grocery", "Beverages", "Spices", "More"];

export const indianStates = [
  "Andhra Pradesh",
  "Delhi",
  "Gujarat",
  "Karnataka",
  "Maharashtra",
  "Tamil Nadu",
  "Telangana",
  "Uttar Pradesh",
  "West Bengal",
];

export const citiesByState: Record<string, string[]> = {
  "Andhra Pradesh": ["Vijayawada", "Visakhapatnam"],
  Delhi: ["New Delhi"],
  Gujarat: ["Ahmedabad", "Surat"],
  Karnataka: ["Bengaluru", "Mysuru"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur"],
  "Tamil Nadu": ["Chennai", "Coimbatore"],
  Telangana: ["Hyderabad", "Warangal"],
  "Uttar Pradesh": ["Lucknow", "Noida"],
  "West Bengal": ["Kolkata"],
};
